[build]
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/public/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/public/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin-dashboard"
  to = "/public/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/admin_dashboard"
  to = "/public/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
